language: node_js
node_js:
    - "10.16.3"
script:
    - echo "Deploying!"
install:
    - npm install -g firebase-tools
after_success:
    - firebase use default
    - firebase deploy --project chillieguy-afe82 --token $FIREBASE_TOKEN
