language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  project: chillieguy
  token:
    secure: "qGPimkhYDoHfVnlL9bMSc5Ja18fl7Uz9/5WhHTFLbsL91fbxmrXvum59P37ZhNnHkpE5tKF+Gvuh4ZkBKwGyYHQAMB56BfKDr5lWGQxZdsM0MHji/nuRXJ0tt2yjrDUipjKLzxUplxxrt+V+hQKTsSTy2ZuoMpqnjP6LwITCyo2OrKv2tvo3ff7lh6NcUtxsh78oWYmlHnaOcQp9k6FoOpuolVUx28E77zuItER33KWxvUqwR2WSNBFrCBSRiQ1UysprFyvChebCi3ZIBiyGIGKNq9tZO0bCunK8dilDiHIG1ggNfOVZXPrwA2/7Jm60xMiNxk10iNIc+0eagIXpGo0tNm23JkVBH2MMcXb1b2HwovD3xOvYnPDfVKhgGHuEMP+VuRFq/kEpJUKM/BYtGMkYGQph/uD/2b36QG/WCu7ZNjg13wg4KMKkF0EQUODeZSUuNN5+wI9Vw4sfJxuq/d7vG8kplbLPmvHpk2RNVFv50BdMC2u7BtbBp8ghpnmcKI2ZR5PUkrStOo3cyuiMK4gMzswtC6Z0whuMzKo2ZGvdRJ32cbxVShYxS4a/SS+2uJ3JTjpej/ZuAkirwyD1/DBNiyAWuWWqdw8QJ6gBwiGJpK81pdKrbo89IRmQI+b2636Yn15pb24Il66xy6evws1k8ODEGAfqfziOCbVr3RA="